### ISSUE TITLE
If you're still working on this, probably not but worth a try

### ISSUE THREAD

**Issue by MrRubberDucky** [LoganDark/fabric-command-hider#1]
Stops datapacks from loading and well existing.
```
[22:12:23] [Worker-Main-11/ERROR]: Failed to load function incendium:border_of_life/notes/790
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "net.minecraft.server.MinecraftServer.method_3734()" because the return value of "net.minecraft.class_2168.method_9211()" is null
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.server.MinecraftServer.method_3734()" because the return value of "net.minecraft.class_2168.method_9211()" is null
	at net.logandark.commandhider.CommandHider.getPrefix(CommandHider.java:39) ~[command-hider-0.2.0.jar:?]
	at com.mojang.brigadier.tree.CommandNode.handler$dah000$commandHider$onCanUse(CommandNode.java:630) ~[brigadier-1.0.18.jar:?]
	at com.mojang.brigadier.tree.CommandNode.canUse(CommandNode.java:65) ~[brigadier-1.0.18.jar:?]
	at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:358) ~[brigadier-1.0.18.jar:?]
	at com.mojang.brigadier.CommandDispatcher.parse(CommandDispatcher.java:348) ~[brigadier-1.0.18.jar:?]
	at net.minecraft.class_2158.method_9195(class_2158.java:56) ~[server-intermediary.jar:?]
	at net.minecraft.class_5349.method_29451(class_5349.java:85) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	... 6 more
```

Thought I would let you know since you posted it long time ago on fabric discord and i just recently gotten around to playing with it and it like fits my needs perfectly

**Comment by LoganDark** [comment]
Could you upload a data pack that reproduces the issue? I can't check it out rn but I don't use data packs so I have nothing to test with

**Comment by MrRubberDucky** [comment]
> Could you upload a data pack that reproduces the issue? I can't check it out rn but I don't use data packs so I have nothing to test with

Yea sure, here's [Incendium](https://www.curseforge.com/minecraft/mc-mods/incendium) and here's another one for [creative dimension](https://www.planetminecraft.com/data-pack/datapack-superflat-creative-dimension-the-dream-world-mc-1-18/), this one loads but doesn't create any scoreboard objectives that it needs which effectively makes the datapack unusable (and even if it does then the rest doesn't work still like creating creative dim portal)

**Comment by LoganDark** [comment]
Looks like datapacks apparently have `ServerCommandSource`s without an associated server. Fixed: https://github.com/LoganDark/fabric-command-hider/releases/tag/v0.2.1

And sorry for taking so long

**Comment by LoganDark** [comment]
I looked into this more and apparently as part of the static datapack validation, Minecraft parses every command with the server's `CommandDispatcher`. Annoyingly, it doesn't fill in the `ServerCommandSource`'s server for that (because it doesn't even have access to the server).

Command Hider now just falls back to vanilla behavior in this scenario, just like it does with modded `CommandDispatcher`s.
